### ISSUE TITLE
Add nod to 'Salvation' reference

### ISSUE THREAD

**Issue by makinako** [Laurelai/decompile-dump#3]
In the new Netflix TV series 'Salvation' S01E12 (The Wormwood Prophecy), I noticed some familiarity in some of their hack-the-matrix scrolling code (at time 21:50, noting Netflix shows time remaining, not elapsed):

![image](https://user-images.githubusercontent.com/31508092/39405776-dc9a8660-4bee-11e8-8883-331e50e9087d.png)

It seems that Stuxnet is the hacker code of choice for MovieOS! I saw the Startrek Discovery link on the Readme.md and thought you may want to add.

**Comment by Laurelai** [comment]
Sure thing.
